services:
  main:
    image: ghcr.io/schwungus/nutpuncher
    container_name: nutpuncher
    network_mode: host # kludge, required: just forwarding port 30001 breaks nutpuncher connectivity for unknown reasons
    restart: always
    tty: true # kludge, required: the Windows binary doesn't run at all without this
