name: Deploy the public instance

on:
  # redeploy only on direct modifications of the NutPuncher code
  push:
    branches: [ master ]
    paths: [ src/NutPuncher.cpp ]

  # OR trigger deployment manually in case the modifications in NutPunch.h matter to the server since it reuses some of its funcs
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure
        run: cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D
          NUTPUNCH_BUILD_SERVER=ON
      - name: Build
        run: cmake --build build --target NutPuncher
      - name: Upload binary artifact
        uses: appleboy/scp-action@v1
        with:
          host: nutpunch.schwung.us
          username: ${{ secrets.PUBLIC_INSTANCE_USER }}
          key: ${{ secrets.PUBLIC_INSTANCE_SSH_KEY }}
          source: build/NutPuncher
          target: /tmp
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: nutpunch.schwung.us
          username: ${{ secrets.PUBLIC_INSTANCE_USER }}
          key: ${{ secrets.PUBLIC_INSTANCE_SSH_KEY }}
          script: |
            set -e

            TMPPATH=/tmp/build/NutPuncher
            chmod +x $TMPPATH

            PORT=$($TMPPATH a b c)
            systemctl --user stop NutPuncher@$PORT || :
            cp $TMPPATH NutPuncher-$PORT
            systemctl --user enable NutPuncher@$PORT || :
            systemctl --user restart NutPuncher@$PORT

            echo Restarted the NutPuncher service on port $PORT
