name: Publish NutPuncher for major platforms

on:
  push:
    tags: [rolling]

jobs:
  binary:
    name: Upload binaries for ${{ matrix.os-name }}
    runs-on: ${{ matrix.runner-os }}
    env:
      BINARY: NutPuncher-${{ matrix.os-name }}${{ matrix.bin-ext }}
    strategy:
      matrix:
        include:
          - os-name: Windows
            runner-os: windows-2022
            bin-ext: .exe
          - os-name: Linux
            runner-os: ubuntu-24.04
            bin-ext: ""
            deploy: true
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure
        run: cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D NUTPUNCH_BUILD_SERVER=ON ${{ github.ref_name == 'staging' && '-D NUTPUNCH_STAGING=ON' || '' }}
      - name: Build
        run: cmake --build build --target NutPuncher
      - name: Rename binary artifact
        # Expand `$BINARY` directly since pwsh wants `$env:BINARY`, while bash accepts `$BINARY`, which confuses the command run between those two shells.
        run: cp build/NutPuncher${{ matrix.bin-ext }} ${{ env.BINARY }}
      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BINARY }}
      - name: Deploy
        uses: appleboy/ssh-action@v1
        if: matrix.deploy
        env:
          TMPPATH: /tmp/NutPuncher-${{ github.ref_name }}
          OUTPATH: /usr/local/bin/NutPuncher
        with:
          host: nutpunch.schwung.us
          username: root
          key: ${{ secrets.PUBLIC_INSTANCE_SSH_KEY }}
          envs: TMPPATH,OUTPATH
          script: |
            wget -O $TMPPATH https://github.com/Schwungus/nutpunch/releases/download/rolling/NutPuncher-Linux
            chmod +x $TMPPATH
            PORT=$($TMPPATH a b c)
            systemctl stop nutpuncher@$PORT || true
            cp $TMPPATH ${OUTPATH}-$PORT
            systemctl restart nutpuncher@$PORT && echo Restarted service || exit 1
